# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ftpuser/wiser/wiser/wiser/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ftpuser/wiser/wiser/wiser/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ftpuser/wiser/wiser/wiser/trunk/CMakeFiles /home/ftpuser/wiser/wiser/wiser/trunk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ftpuser/wiser/wiser/wiser/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

database.o: database.c.o

.PHONY : database.o

# target to build an object file
database.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/database.c.o
.PHONY : database.c.o

database.i: database.c.i

.PHONY : database.i

# target to preprocess a source file
database.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/database.c.i
.PHONY : database.c.i

database.s: database.c.s

.PHONY : database.s

# target to generate assembly for a file
database.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/database.c.s
.PHONY : database.c.s

mongodatabase.o: mongodatabase.c.o

.PHONY : mongodatabase.o

# target to build an object file
mongodatabase.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mongodatabase.c.o
.PHONY : mongodatabase.c.o

mongodatabase.i: mongodatabase.c.i

.PHONY : mongodatabase.i

# target to preprocess a source file
mongodatabase.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mongodatabase.c.i
.PHONY : mongodatabase.c.i

mongodatabase.s: mongodatabase.c.s

.PHONY : mongodatabase.s

# target to generate assembly for a file
mongodatabase.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mongodatabase.c.s
.PHONY : mongodatabase.c.s

myclient.o: myclient.c.o

.PHONY : myclient.o

# target to build an object file
myclient.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/myclient.c.o
.PHONY : myclient.c.o

myclient.i: myclient.c.i

.PHONY : myclient.i

# target to preprocess a source file
myclient.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/myclient.c.i
.PHONY : myclient.c.i

myclient.s: myclient.c.s

.PHONY : myclient.s

# target to generate assembly for a file
myclient.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/myclient.c.s
.PHONY : myclient.c.s

postings.o: postings.c.o

.PHONY : postings.o

# target to build an object file
postings.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/postings.c.o
.PHONY : postings.c.o

postings.i: postings.c.i

.PHONY : postings.i

# target to preprocess a source file
postings.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/postings.c.i
.PHONY : postings.c.i

postings.s: postings.c.s

.PHONY : postings.s

# target to generate assembly for a file
postings.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/postings.c.s
.PHONY : postings.c.s

search.o: search.c.o

.PHONY : search.o

# target to build an object file
search.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/search.c.o
.PHONY : search.c.o

search.i: search.c.i

.PHONY : search.i

# target to preprocess a source file
search.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/search.c.i
.PHONY : search.c.i

search.s: search.c.s

.PHONY : search.s

# target to generate assembly for a file
search.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/search.c.s
.PHONY : search.c.s

testmongodatabase.o: testmongodatabase.c.o

.PHONY : testmongodatabase.o

# target to build an object file
testmongodatabase.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/testmongodatabase.c.o
.PHONY : testmongodatabase.c.o

testmongodatabase.i: testmongodatabase.c.i

.PHONY : testmongodatabase.i

# target to preprocess a source file
testmongodatabase.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/testmongodatabase.c.i
.PHONY : testmongodatabase.c.i

testmongodatabase.s: testmongodatabase.c.s

.PHONY : testmongodatabase.s

# target to generate assembly for a file
testmongodatabase.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/testmongodatabase.c.s
.PHONY : testmongodatabase.c.s

token.o: token.c.o

.PHONY : token.o

# target to build an object file
token.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/token.c.o
.PHONY : token.c.o

token.i: token.c.i

.PHONY : token.i

# target to preprocess a source file
token.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/token.c.i
.PHONY : token.c.i

token.s: token.c.s

.PHONY : token.s

# target to generate assembly for a file
token.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/token.c.s
.PHONY : token.c.s

util.o: util.c.o

.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i

.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s

.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/util.c.s
.PHONY : util.c.s

wikiload.o: wikiload.c.o

.PHONY : wikiload.o

# target to build an object file
wikiload.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/wikiload.c.o
.PHONY : wikiload.c.o

wikiload.i: wikiload.c.i

.PHONY : wikiload.i

# target to preprocess a source file
wikiload.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/wikiload.c.i
.PHONY : wikiload.c.i

wikiload.s: wikiload.c.s

.PHONY : wikiload.s

# target to generate assembly for a file
wikiload.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/wikiload.c.s
.PHONY : wikiload.c.s

wiser.o: wiser.c.o

.PHONY : wiser.o

# target to build an object file
wiser.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/wiser.c.o
.PHONY : wiser.c.o

wiser.i: wiser.c.i

.PHONY : wiser.i

# target to preprocess a source file
wiser.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/wiser.c.i
.PHONY : wiser.c.i

wiser.s: wiser.c.s

.PHONY : wiser.s

# target to generate assembly for a file
wiser.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/wiser.c.s
.PHONY : wiser.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... database.o"
	@echo "... database.i"
	@echo "... database.s"
	@echo "... mongodatabase.o"
	@echo "... mongodatabase.i"
	@echo "... mongodatabase.s"
	@echo "... myclient.o"
	@echo "... myclient.i"
	@echo "... myclient.s"
	@echo "... postings.o"
	@echo "... postings.i"
	@echo "... postings.s"
	@echo "... search.o"
	@echo "... search.i"
	@echo "... search.s"
	@echo "... testmongodatabase.o"
	@echo "... testmongodatabase.i"
	@echo "... testmongodatabase.s"
	@echo "... token.o"
	@echo "... token.i"
	@echo "... token.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... wikiload.o"
	@echo "... wikiload.i"
	@echo "... wikiload.s"
	@echo "... wiser.o"
	@echo "... wiser.i"
	@echo "... wiser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

